version: "3.7"

services:

  dev_db:
    image: postgres:17.3
    container_name: pg_turbo_dev
    environment:
      - POSTGRES_USER=turbo
      - POSTGRES_PASSWORD=turbo
      - POSTGRES_DB=turbo_dev
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./priv/support/create_test_db.sql:/docker-entrypoint-initdb.d/1-schema.sql

volumes:
  db:
