volumes:
  pg_data: {}

services:
  turbo_racer_app:
    image: brunojppb/turbo-racer:latest
    container_name: turbo_racer_app
    environment:
      # Postgres database URL pattern expected by Ecto: postgres://USER:PASS@HOST/DATABASE
      - DATABASE_URL=postgres://turbo_racer:please_replace_me@turbo_racer_db/turbo_racer
      # If you want to use SSL when connecting to your DB
      # - USE_DB_SSL=1
      - SECRET_KEY_BASE=please_replace_me_with_something_random_and_strong_at_least_64_characters_long
      - PHX_HOST=localhost
      - PORT=4000
      # By default, Artifacts older than 90 days will be deleted to reduce disk usage/S3 bill.
      # But you can configure it for longer or shorter periods with the following variable
      # - ARTIFACT_BUSTING_IN_DAYS=90
      # Whether HTTPS should be enabled to the URL scheme
      # - USE_HTTPS=1 (uses http by default)
      #
      # If you want to use a S3-compatible storage for your artifacts,
      # Add the following environment variables
      # - S3_BUCKET_NAME=bucket_name
      # - S3_ACCESS_KEY_ID=access_key_id
      # - S3_SECRET_ACCESS_KEY=secret_access_key
      # - S3_HOST=s3_host

    depends_on:
      turbo_racer_db:
        condition: service_healthy
    ports:
      - "4000:4000"
    volumes:
      - ./docker_turbo_artifacts:/var/turbo_artifacts
  turbo_racer_db:
    image: postgres:17.2
    container_name: turbo_racer_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U turbo_racer"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=turbo_racer
      - POSTGRES_PASSWORD=please_replace_me
      - POSTGRES_DB=turbo_racer
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
