name: Docker Build
on:
  pull_request:
  workflow_dispatch:
    inputs: {}
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read app version
        id: app-version
        run: |
          APP_VERSION_FROM_MIX=$(grep "version: " mix.exs | grep -o "[0-9.]*")
          echo "App version from mix: ${APP_VERSION_FROM_MIX}"
          echo "APP_VERSION=$APP_VERSION_FROM_MIX" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: brunojppb
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: docker build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: "linux/amd64,linux/arm64"
          # push: ${{ github.event_name != 'pull_request' }}
          push: false
          tags: "brunojppb/turbo-racer:latest,brunojppb/turbo-racer:${{ steps.app-version.outputs.APP_VERSION }}"
          cache-from: type=registry,ref=brunojppb/turbo-racer:latest
          cache-to: type=inline

      # - name: login to Github Container registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: push to Github Container Registry
      #   run: |
      #     docker pull brunojppb/turbo-racer:${{ steps.app-version.outputs.APP_VERSION }}
      #     docker pull brunojppb/turbo-racer:latest
      #     docker tag brunojppb/turbo-racer:${{ steps.app-version.outputs.APP_VERSION }} ghcr.io/brunojppb/turbo-racer:${{ steps.app-version.outputs.APP_VERSION }}
      #     docker tag brunojppb/turbo-racer:latest ghcr.io/brunojppb/turbo-racer:latest
      #     docker push ghcr.io/brunojppb/turbo-racer:latest
      #     docker push ghcr.io/brunojppb/turbo-racer:${{ steps.app-version.outputs.APP_VERSION }}
